const catsCategoryData = {
  name: "Cats",
  isCustom: true,
  subCategories: [
    {
      title: "Cat Food",
      items: ["Dry Food", "Wet Food", "Grain Free", "Prescription Diet"],
    },
    {
      title: "Cat Toys",
      items: ["Interactive Toys", "Feather Toys", "Treat Toys"],
    },
    {
      title: "Dog Food",
      items: [
        "Dry Food",
        "Wet Food",
        "Puppy Food",
        "Grain Free Food",
        "Baked Dry Food",
        "Veg Dog Food",
        "Premium Dog Food",
        "Prescription Diet",
      ],
    },
    {
      title: "Dog Treats & Chews",
      items: [
        "Biscuits & Cookies",
        "Bones & Chews",
        "Dental Treats",
        "Jerky Treats",
        "Training Treats",
        "Calcium Bones",
      ],
    },
    {
      title: "Pharmacy",
      items: [
        "Prescription Diet",
        "Dewormer",
        "Tick & Flea",
        "Skin Care",
        "Joint Care",
        "Gut Health",
        "Cardiac Care",
        "Kidney Care",
        "Liver Care",
        "Eye & Ear Care",
        "Vitamins & Supplements",
      ],
    },
    {
      title: "Walk & Travel Essentials",
      items: [
        "Collars",
        "Leashes",
        "Harnesses",
        "GPS Tracker",
        "Carriers & Travel Supplies",
        "Cages & Crates",
        "Accessories",
      ],
    },
    {
      title: "Dog Toys",
      items: [
        "Chew Toys",
        "Interactive Toys",
        "Plush Toys",
        "Rope & Tug Toys",
        "Ball & Fetch Toys",
        "Squeaky Toys",
        "Treat Dispensing Toys",
      ],
    },
    {
      title: "Dog Clothing",
      items: [
        "Summer Wear",
        "IPL Jerseys",
        "Tshirts & Shirts",
        "Ethnic Wear",
        "Bandanas & Bow-ties",
        "Boots & Socks",
        "Raincoat",
        "Jackets",
        "Sweaters",
        "Winter Wear",
      ],
    },
    {
      title: "Grooming & Beds",
      items: [
        "Shampoos",
        "Brushes & Combs",
        "Tick & Flea Solutions",
        "Deodorants",
        "Towels & Wipes",
        "Training Pads",
        "Pet Cleaners",
        "Beds",
        "Mats",
        "Furniture",
        "Luxury Collection",
      ],
    },
  ],
};
